---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# cmor.tools

<!-- badges: start -->
<!-- badges: end -->

The goal of the CMOR Tools ecosystem is to provide standardised tools to initialise a research project folder, undertake analysis, and generate output reports (journal manuscripts, etc.) for research projects undertaken at CMOR. This package installs and loads all packages in the ecosystem.

## Installation

You can install cmor.tools from [GitHub](https://github.com) with:

``` r
#install.packages("remotes")
remotes::install_github("uo-cmor/cmor.tools")
```

## Packages

`library(cmor.tools)` will load the CMOR Tools packages:

* [`formattr`](https://github.com/uo-cmor/formattr): Format numbers & descriptive statistics nicely for output reports;
* [`CMORprojects`](https://github.com/uo-cmor/CMORprojects): Data analysis project workflow tools;
* [`regtools`](https://github.com/uo-cmor/regtools): Functions for the analysis of regression models;
* [`CMORplots`](https://github.com/uo-cmor/CMORplots): `ggplot` themes and colour palettes for figure formatting;
* [`SF6Dvalues`](https://github.com/uo-cmor/SF6Dvalues): Calculate SF-6D health utility values from SF-12/SF-36 questionnaires;
* [`cea`](https://github.com/uo-cmor/cea): Tools for trial-based cost-effectiveness analyses.
